# Generated by Django 4.0.6 on 2022-08-04 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Student',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sname', models.CharField(blank=True, max_length=100)),
                ('gpa', models.DecimalField(decimal_places=2, max_digits=4)),
                ('email', models.EmailField(max_length=100)),
                ('human', models.BooleanField(default=False)),
            ],
        ),
    ]
