# Generated by Django 4.0.6 on 2022-08-04 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_student_slug'),
    ]

    operations = [
        migrations.AlterField(
            model_name='student',
            name='human',
            field=models.BooleanField(blank=True, default=False),
        ),
    ]
